apiVersion: v1
kind: Service
metadata:
  name: authz
  labels:
    app: authz
spec:
#  type: LoadBalancer
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: authz
